# linux_data.py

# List 1: The Questions (What does the command do?)
questions = [
    "List all files and directories in the current folder",
    "Change directory",
    "Print the current working directory path",
    "Make a new directory",
    "Remove a file",
    "Remove a directory and its contents recursively",
    "Copy a file",
    "Move or rename a file",
    "Create an empty file",
    "View the contents of a file",
    "View the first 10 lines of a file",
    "View the last 10 lines of a file",
    "Search for a specific text string inside a file",
    "Display the manual/help page for a command",
    "Clear the terminal screen",
    "Show the current username",
    "Show the current date and time",
    "Display disk space usage",
    "Display memory (RAM) usage",
    "Show currently running processes",
    "Kill a process by its ID",
    "Change file permissions",
    "Change file owner",
    "Execute a command with superuser (admin) privileges",
    "Update package lists (on Ubuntu/Debian)",
    "Install a package (on Ubuntu/Debian)",
    "Check network interface details (IP address, etc.)",
    "Check if a website or server is reachable",
    "Download a file from the internet",
    "Extract a .tar.gz file",
    "Compress files into a zip archive",
    "Unzip a zip archive",
    "Check the history of previous commands",
    "Count lines, words, and characters in a file",
    "Display a line of text / print to screen",
    "Find files matching a pattern",
    "Show the location of a binary/executable",
    "Create a shortcut (symbolic link) to a file",
    "Check the kernel version",
    "Display calendar",
    "Exit the terminal",
    "Shutdown the system immediately",
    "Reboot the system",
    "Show hidden files in the current directory",
    "Switch to a different user",
    "Check disk usage of a specific directory",
    "View file contents page by page",
    "Edit a file using the Nano text editor",
    "Edit a file using the Vim text editor",
    "Print system information"
]

# List 2: The Answers (The actual command)
answers = [
    "ls",
    "cd",
    "pwd",
    "mkdir",
    "rm",
    "rm -rf",
    "cp",
    "mv",
    "touch",
    "cat",
    "head",
    "tail",
    "grep",
    "man",
    "clear",
    "whoami",
    "date",
    "df",
    "free",
    "top",
    "kill",
    "chmod",
    "chown",
    "sudo",
    "sudo apt update",
    "sudo apt install",
    "ifconfig",
    "ping",
    "wget",
    "tar -xvf",
    "zip",
    "unzip",
    "history",
    "wc",
    "echo",
    "find",
    "which",
    "ln -s",
    "uname -r",
    "cal",
    "exit",
    "shutdown now",
    "reboot",
    "ls -a",
    "su",
    "du",
    "less",
    "nano",
    "vim",
    "uname -a"
]